name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: ファイル構成が等しいことを確認
      run: |
        en="$(ls original-en | tr -d [:cntrl:][:space:])"
        ja="$(ls translation-ja | tr -d [:cntrl:][:space:])"
        if test "${en}" != "${ja}"; then echo ディレクトリ中のMarkdownファイルの構成が一致しません。; exit 1; fi
